name: dating
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  google_maps_flutter: ^2.5.3
  image_picker: ^1.0.7
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  twitter_login: ^4.4.2
  provider: ^6.1.1
  intl_phone_field: ^3.2.0
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  fluttertoast: ^8.2.4
  geolocator: ^11.0.0
  geocoding: ^2.2.0
  shared_preferences: ^2.2.2
  otp_text_field: ^1.1.3
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_localization: ^0.2.0
  lottie: ^3.1.0
  cloud_firestore: ^4.13.4
  firebase_messaging: ^14.7.7
  flutter_local_notifications: ^9.7.0
  intl:
  agora_rtc_engine: ^6.3.0
  permission_handler: ^11.2.0
  razorpay_flutter: ^1.3.5
  package_info_plus: ^4.0.2
  share_plus:
  sign_in_with_apple:
  crypto: ^3.0.1
  flutter_widget_from_html_core:
  camera: ^0.10.5+9
  webview_flutter: ^3.0.4
  flutter_spinkit: ^5.2.0
  http_auth: ^1.0.4
  get: ^4.6.6
  onesignal_flutter: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/Image/
    - assets/lottie/
    - lang/

  fonts:
    - family: Satoshi-Regular
      fonts:
        - asset: assets/fonts/Satoshi-Regular.otf
    - family: Satoshi-Bold
      fonts:
        - asset: assets/fonts/Satoshi-Bold.otf
    - family: Satoshi-Medium
      fonts:
        - asset: assets/fonts/Satoshi-Medium.otf
    - family: Satoshi-Black
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
